version: '3.9'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "123Mudar!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data